FROM python:3.10

WORKDIR /app

RUN apt-get update
RUN apt-get install \
    'ffmpeg'\
    'libsm6'\
    'libxext6'  -y
RUN pip3 install torchaudio --extra-index-url https://download.pytorch.org/whl/cpu

COPY . .

RUN pip install -e .

EXPOSE 8080

CMD ["python3", "api.py"]
