version : '3.4'
services:
    model_serving_api:
      #build: .
      image: bhossein/facebook_marketplace_rrs
      ports: 
        - 8081:8080
      restart: always
      network_mode: host
      volumes: 
        - /Users/behzad/AiCore/Facebook_Marketplace_RRS/Docker_Api:/app